//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_WEB.Models.TestModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_MST
    {
        public string CODE { get; set; }
        public string CDESCRIP { get; set; }
        public string DESCRIP { get; set; }
        public string SPEC { get; set; }
        public string UNIT { get; set; }
        public Nullable<short> U_CONVERT { get; set; }
        public string METAL { get; set; }
        public string MATERIAL { get; set; }
        public string CLASS_F { get; set; }
        public string CLASS_S { get; set; }
        public string CLASS { get; set; }
        public string P_MODE { get; set; }
        public string ACCT_ID { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> PRICE_S { get; set; }
        public string DRAW_MAN { get; set; }
        public string PAPER_SIZE { get; set; }
        public string DW_LOCATE { get; set; }
        public string DOC_NR { get; set; }
        public string UP_DATE { get; set; }
        public string QC_MK { get; set; }
        public string VENDOR { get; set; }
        public string PROJECT { get; set; }
        public Nullable<byte> LD_TIME { get; set; }
        public string P_KIND { get; set; }
        public string NOTE { get; set; }
        public Nullable<decimal> PRICE_C { get; set; }
        public Nullable<decimal> WEIGTH { get; set; }
        public string ESPEC { get; set; }
        public string CLR_NR { get; set; }
        public string CST_NR { get; set; }
        public string ORIGIN { get; set; }
        public Nullable<decimal> PRICE_P { get; set; }
        public string ORG_CODE { get; set; }
        public string WOOL_CODE { get; set; }
        public string STOP_SALES { get; set; }
    }
}
