//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 之類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 台灣麗偉 版權所有 © 2017 資訊課 的當地語系化字串。
        /// </summary>
        internal static string CopyrightInformation {
            get {
                return ResourceManager.GetString("CopyrightInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        internal static string FormAdd {
            get {
                return ResourceManager.GetString("FormAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        internal static string FormDel {
            get {
                return ResourceManager.GetString("FormDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改 的當地語系化字串。
        /// </summary>
        internal static string FormEdit {
            get {
                return ResourceManager.GetString("FormEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢 的當地語系化字串。
        /// </summary>
        internal static string FormSelect {
            get {
                return ResourceManager.GetString("FormSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 送出 的當地語系化字串。
        /// </summary>
        internal static string FormSumbit {
            get {
                return ResourceManager.GetString("FormSumbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 info@leadwell.com.tw 的當地語系化字串。
        /// </summary>
        internal static string ITEmail {
            get {
                return ResourceManager.GetString("ITEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇語言 的當地語系化字串。
        /// </summary>
        internal static string LangDropdown {
            get {
                return ResourceManager.GetString("LangDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 台灣麗偉EIP系統 的當地語系化字串。
        /// </summary>
        internal static string LeadwellEIP {
            get {
                return ResourceManager.GetString("LeadwellEIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 台灣麗偉電腦機械股份有限公司 的當地語系化字串。
        /// </summary>
        internal static string LeadwellTitle {
            get {
                return ResourceManager.GetString("LeadwellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號 的當地語系化字串。
        /// </summary>
        internal static string LoginID {
            get {
                return ResourceManager.GetString("LoginID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 台灣麗偉-登入頁 的當地語系化字串。
        /// </summary>
        internal static string LoginLeadwellTitle {
            get {
                return ResourceManager.GetString("LoginLeadwellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼 的當地語系化字串。
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 台灣麗偉-登出頁 的當地語系化字串。
        /// </summary>
        internal static string LogoutLeadwellTitle {
            get {
                return ResourceManager.GetString("LogoutLeadwellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用程式 的當地語系化字串。
        /// </summary>
        internal static string MenuSidebarApplication {
            get {
                return ResourceManager.GetString("MenuSidebarApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 行事曆 的當地語系化字串。
        /// </summary>
        internal static string MenuSidebarCalendar {
            get {
                return ResourceManager.GetString("MenuSidebarCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 說明 的當地語系化字串。
        /// </summary>
        internal static string MenuSidebarExplan {
            get {
                return ResourceManager.GetString("MenuSidebarExplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 的當地語系化字串。
        /// </summary>
        internal static string MenuSidebarHome {
            get {
                return ResourceManager.GetString("MenuSidebarHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登出 的當地語系化字串。
        /// </summary>
        internal static string MenuSidebarLogout {
            get {
                return ResourceManager.GetString("MenuSidebarLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選單 的當地語系化字串。
        /// </summary>
        internal static string MenuSidebarMenu {
            get {
                return ResourceManager.GetString("MenuSidebarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定 的當地語系化字串。
        /// </summary>
        internal static string MenuSidebarSetup {
            get {
                return ResourceManager.GetString("MenuSidebarSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇語言 的當地語系化字串。
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 英文(美國) 的當地語系化字串。
        /// </summary>
        internal static string SelectLanguageChinessENUS {
            get {
                return ResourceManager.GetString("SelectLanguageChinessENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 中文(簡體) 的當地語系化字串。
        /// </summary>
        internal static string SelectLanguageChinessZHCN {
            get {
                return ResourceManager.GetString("SelectLanguageChinessZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 中文(繁體) 的當地語系化字串。
        /// </summary>
        internal static string SelectLanguageChinessZHTW {
            get {
                return ResourceManager.GetString("SelectLanguageChinessZHTW", resourceCulture);
            }
        }
    }
}
